import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ithena - Intelligent Email Management",
  description:
    "Ithena transforms your inbox into actionable tasks with AI-powered analysis. Experience secure and effortless email management that extracts critical tasks from your emails.Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Script
          src="https://datafa.st/js/script.js"
          data-website-id="67acc69653c7643ac65edd51"
          data-domain="www.ithena.one"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
